In [137]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
plt.style.use("ggplot")
%matplotlib inline

In [138]:
from transform import get_X_y
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [139]:
## import sklearn modules

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error

from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

In [140]:
orbit2b = pd.read_csv('../data/samples_2_bodies_3_dim_1_m_com.csv')

In [141]:
orbit2b.head()

sim_id  m_1  m_2    rx_1_0    ry_1_0    rz_1_0    rx_2_0    ry_2_0  \
0     0.0  1.0  1.0  0.072812  0.339681  0.234807 -0.072812 -0.339681   
1     0.0  1.0  1.0  0.054407  0.105241  0.222055 -0.054407 -0.105241   
2     0.0  1.0  1.0  0.015466 -0.034834  0.083430 -0.015466  0.034834   
3     0.0  1.0  1.0  0.060140  0.364899  0.167492 -0.060140 -0.364899   
4     0.0  1.0  1.0  0.017181  0.251330  0.001720 -0.017181 -0.251330   

     rz_2_0    vx_1_0  ...  rz_1_1000  rx_2_1000  ry_2_1000  rz_2_1000  \
0 -0.234807  0.032668  ...   0.245414  -0.062839  -0.156803  -0.245414   
1 -0.222055 -0.151459  ...   0.001457  -0.017101  -0.250963  -0.001457   
2 -0.083430 -0.452646  ...   0.080874  -0.039404  -0.331130  -0.080874   
3 -0.167492  0.083064  ...   0.261195  -0.074577  -0.281935  -0.261195   
4 -0.001720  0.167503  ...   0.181902  -0.063202  -0.364724  -0.181902   

   vx_1_1000  vy_1_1000  vz_1_1000  vx_2_1000  vy_2_1000  vz_2_1000  
0  -0.104210  -0.721673  -0.262195   0.104210   0.721673   0.262195  
1   0.167632   0.763737   0.546329  -0.167632  -0.763737  -0.546329  
2   0.128510   0.343728   0.494653  -0.128510  -0.343728  -0.494653  
3  -0.013481  -0.439943   0.074785   0.013481   0.439943  -0.074785  
4   0.074315  -0.030131   0.357845  -0.074315   0.030131  -0.357845  

[5 rows x 51 columns]

In [142]:
model = MultiOutputRegressor(GradientBoostingRegressor(n_estimators=100,
                                                        max_depth=10,
                                                        learning_rate=0.05)
                             , n_jobs=-1)

In [143]:
steps = 10
X, y = get_X_y(orbit2b, steps, False, True)

In [144]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [145]:
model.fit(X_train, y_train);

In [146]:
y_pred = model.predict(X_test)

In [147]:
print(steps, np.sqrt(mean_squared_error(y_test, y_pred)))

10 0.21754216531914175


In [148]:
y_test[0], y_pred[0]

(array([ 1.42437385,  0.67171848,  1.82241203, -0.02767831, -0.70740949,
         0.35498871]),
 array([ 1.42025141,  0.66808496,  1.81299781, -0.02475706, -0.7082653 ,
         0.36889454]))

In [149]:
steps = 100
X, y = get_X_y(orbit2b, steps, False, True)

In [150]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [ ]:
model.fit(X_train, y_train);

In [152]:
y_pred = model.predict(X_test)

In [153]:
print(steps, np.sqrt(mean_squared_error(y_test, y_pred)))

100 0.4091465745889179


In [154]:
y_test[0], y_pred[0]

(array([-0.14758085, -0.37569056,  0.14941897, -0.56375713,  0.26813841,
         1.28058813]),
 array([-0.14344678, -0.08456889,  0.36370579,  0.15232801,  0.10727379,
        -0.27646432]))

In [155]:
steps = 1000
X, y = get_X_y(orbit2b, steps, False, True)

In [156]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [ ]:
model.fit(X_train, y_train);

In [158]:
y_pred = model.predict(X_test)

In [159]:
print(steps, np.sqrt(mean_squared_error(y_test, y_pred)))

1000 0.6803796973228321


In [160]:
y_test[0], y_pred[0]

(array([ 4.1987364 , 19.63682265, -1.70664892,  0.25519243,  0.87322717,
        -0.13023219]),
 array([ 4.15682174, 19.57090257, -1.33027238,  0.17980312,  0.85356376,
        -0.07148126]))