In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
plt.style.use("ggplot")
%matplotlib inline

In [20]:
from transform import get_X_y
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [21]:
## import sklearn modules

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error

from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

In [22]:
orbit3b = pd.read_csv('../data/samples_3_bodies_3_dim_0_m_com.csv')

In [23]:
orbit3b.head()

sim_id       m_1       m_2       m_3    rx_1_0    ry_1_0    rz_1_0  \
0     0.0  1.612215  2.697331  2.113259 -2.296006  2.877565 -9.170347   
1     0.0  1.612215  2.697331  2.113259 -0.833236  2.025081 -4.682410   
2     0.0  1.612215  2.697331  2.113259 -1.386685  2.451587 -6.523806   
3     0.0  1.612215  2.697331  2.113259 -1.704009  2.637154 -7.498272   
4     0.0  1.612215  2.697331  2.113259 -2.050488  2.794998 -8.500527   

     rx_2_0    ry_2_0    rz_2_0  ...  rz_3_1000  vx_1_1000  vy_1_1000  \
0  0.706297 -0.899724  3.160373  ...   3.475327  -0.083728  -0.005456   
1  0.218571 -0.615884  1.653333  ...   2.564054  -0.142035   0.065775   
2  0.407949 -0.761911  2.265831  ...   2.923653  -0.120877   0.036916   
3  0.517432 -0.837350  2.580210  ...   3.123465  -0.108443   0.021664   
4  0.619787 -0.874291  2.936525  ...   3.362595  -0.094319   0.005680   

   vz_1_1000  vx_2_1000  vy_2_1000  vz_2_1000  vx_3_1000  vy_3_1000  vz_3_1000  
0  -0.182062  -0.644452   0.732823   1.021511   0.886446  -0.931201  -1.164945  
1  -0.412336  -0.434259   0.539911   0.856111   0.662640  -0.739314  -0.778154  
2  -0.324624  -0.367041   0.482402   0.731627   0.560703  -0.643894  -0.686181  
3  -0.275432   0.570784  -0.428765  -0.544556  -0.645808   0.530742   0.905192  
4  -0.221403   1.123254  -1.029775  -1.358825  -1.361748   1.310056   1.903292  

[5 rows x 76 columns]

In [24]:
model = MultiOutputRegressor(GradientBoostingRegressor(n_estimators=100,
                                                        max_depth=10,
                                                        learning_rate=0.05)
                             , n_jobs=-1)

In [25]:
steps = 10
X, y = get_X_y(orbit3b, steps, True, True)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [27]:
model.fit(X_train, y_train);

In [28]:
y_pred = model.predict(X_test)

In [29]:
print(steps, np.sqrt(mean_squared_error(y_test, y_pred)))

10 0.926865444562274


In [30]:
y_test[0], y_pred[0]

(array([ 0.22719298, -0.10538213, -0.73245808,  2.11359199,  0.05369671,
        -0.17770615, -0.13721558,  0.80944048,  0.75247342,  0.48198724,
         1.30925544,  0.84282245]),
 array([ 0.22340024, -0.09584466, -0.7352909 ,  2.10702361,  0.04475249,
        -0.16436548, -0.24014472,  1.05423607,  0.81756974,  0.19919779,
         0.92862919,  0.93334365]))

In [31]:
steps = 100
X, y = get_X_y(orbit3b, steps, True, True)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [33]:
model.fit(X_train, y_train);

In [34]:
y_pred = model.predict(X_test)

In [35]:
print(steps, np.sqrt(mean_squared_error(y_test, y_pred)))

100 1.3189722859293307


In [36]:
y_test[0], y_pred[0]

(array([ 1.15839744, -0.00426382,  0.14910177,  0.47946344,  0.21177181,
        -0.25817711,  1.22061501, -1.4140772 , -3.0122764 ,  0.44040862,
        -3.1143608 , -1.49056966]),
 array([-0.0426533 ,  0.04496503,  0.73020472, -0.05924909,  0.45660182,
         0.12221846,  0.09023838, -0.16839759, -0.99990985,  0.03844903,
        -0.23198878, -0.15609391]))

In [37]:
steps = 1000
X, y = get_X_y(orbit3b, steps, True, True)

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [39]:
model.fit(X_train, y_train);

In [40]:
y_pred = model.predict(X_test)

In [41]:
print(steps, np.sqrt(mean_squared_error(y_test, y_pred)))

1000 2.342292422475718


In [42]:
y_test[0], y_pred[0]

(array([ 0.22698777, -0.43346018, -0.78345512, -0.20692582, -1.32776886,
         0.03241071, -1.28486153, -0.80801258, -0.55344148,  0.19082865,
         1.18835337,  2.09872536]),
 array([-0.10097987, -0.37314307, -0.32845194,  0.12696265,  1.59285194,
        -1.32410305, -0.17394209, -0.21295738,  0.19447635, -0.02039434,
        -0.01486469, -0.11760966]))