In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
plt.style.use("ggplot")
%matplotlib inline

In [2]:
from transform import get_X_y
from transform import inverse_transform_X_y
%load_ext autoreload
%autoreload 2

In [24]:
orbit3b = pd.read_csv('../data/samples_2_bodies_3_dim_1_m_com.csv')

In [25]:
steps = 10
orig_X, _ = get_X_y(orbit3b, steps, False, False)

In [26]:
orig_X[0:2,:]

array([[ 0.07281155,  0.33968053,  0.23480664, -0.07281155, -0.33968053,
        -0.23480664,  0.03266844, -0.2460071 ,  0.23030966, -0.03266844,
         0.2460071 , -0.23030966],
       [ 0.05440708,  0.10524137,  0.2220554 , -0.05440708, -0.10524137,
        -0.2220554 , -0.1514587 , -0.82615856, -0.45092904,  0.1514587 ,
         0.82615856,  0.45092904]])

In [27]:
steps = 10
trans_X, _ = get_X_y(orbit3b, steps, False, True)

In [28]:
trans_X[0:2,:]

array([[-0.1456231 , -0.67936106, -0.46961327, -0.06533689,  0.49201421,
        -0.46061932],
       [-0.10881417, -0.21048273, -0.4441108 ,  0.30291739,  1.65231711,
         0.90185808]])

In [30]:
inv_X = inverse_transform_X_y(trans_X, 2, False)

In [31]:
inv_X[0:2,:]

array([[ 0.07281155,  0.33968053,  0.23480664, -0.07281155, -0.33968053,
        -0.23480664,  0.03266844, -0.2460071 ,  0.23030966, -0.03266844,
         0.2460071 , -0.23030966],
       [ 0.05440708,  0.10524137,  0.2220554 , -0.05440708, -0.10524137,
        -0.2220554 , -0.1514587 , -0.82615856, -0.45092904,  0.1514587 ,
         0.82615856,  0.45092904]])