In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
plt.style.use("ggplot")
%matplotlib inline

In [68]:
from transform import get_X_y
from transform import inverse_transform_X_y
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [69]:
orbit3b = pd.read_csv('../data/samples_3_bodies_3_dim_0_m_com.csv')

In [82]:
steps = 10
orig_X, _ = get_X_y(orbit3b, steps, True, False)

In [83]:
orig_X[0]

array([ 1.61221481,  2.69733117,  2.11325921, -2.29600625,  2.87756519,
       -9.1703469 ,  0.70629746, -0.89972364,  3.16037259,  0.85012626,
       -1.04691399,  2.9622479 , -0.11819034,  0.03352034, -0.31385727,
        0.4553841 , -0.31020747, -0.36746062, -0.49107724,  0.37037117,
        0.70846411])

In [84]:
steps = 10
trans_X, _ = get_X_y(orbit3b, steps, True, True)

In [85]:
trans_X[0]

array([ 1.61221481,  2.69733117,  2.11325921,  3.00230372, -3.77728883,
       12.33071948,  3.14613251, -3.92447918, 12.1325948 ,  0.57357444,
       -0.34372781, -0.05360335, -0.3728869 ,  0.33685083,  1.02232138])

In [95]:
inv_X = inverse_transform_X_y(trans_X, 3, True)

[ 2.29600625 -2.87756519  9.1703469 ]


In [96]:
inv_X[0]

array([ 1.61221481,  2.69733117,  2.11325921, -2.29600625,  2.87756519,
       -9.1703469 ,  0.70629746, -0.89972364,  3.16037259,  0.85012626,
       -1.04691399,  2.9622479 , -0.11819034,  0.03352034, -0.31385727,
        0.4553841 , -0.31020747, -0.36746062, -0.49107724,  0.37037117,
        0.70846411])

In [89]:
m = orig_X[0,:3]
r = orig_X[0, 3:12]
v = orig_X[0, 12:]

((r.reshape((3, 3)).T @ m) / np.sum(m))

array([ 6.91425626e-17, -6.91425626e-17,  2.76570250e-16])

[-2.29600625  2.87756519 -9.1703469   0.70629746 -0.89972364  3.16037259
  0.85012626 -1.04691399  2.9622479 ] [[-2.29600625  2.87756519 -9.1703469 ]
 [ 0.70629746 -0.89972364  3.16037259]
 [ 0.85012626 -1.04691399  2.9622479 ]]
