In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
plt.style.use("ggplot")
%matplotlib inline

In [19]:
from transform import get_X_y
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [20]:
## import sklearn modules

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error

from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

In [21]:
orbit2b = pd.read_csv('../data/samples_2_bodies_3_dim_1_m_com.csv')

In [22]:
orbit2b.head()

sim_id  m_1  m_2    rx_1_0    ry_1_0    rz_1_0    rx_2_0    ry_2_0  \
0     0.0  1.0  1.0  0.072812  0.339681  0.234807 -0.072812 -0.339681   
1     0.0  1.0  1.0  0.054407  0.105241  0.222055 -0.054407 -0.105241   
2     0.0  1.0  1.0  0.015466 -0.034834  0.083430 -0.015466  0.034834   
3     0.0  1.0  1.0  0.060140  0.364899  0.167492 -0.060140 -0.364899   
4     0.0  1.0  1.0  0.017181  0.251330  0.001720 -0.017181 -0.251330   

     rz_2_0    vx_1_0  ...  rz_1_1000  rx_2_1000  ry_2_1000  rz_2_1000  \
0 -0.234807  0.032668  ...   0.245414  -0.062839  -0.156803  -0.245414   
1 -0.222055 -0.151459  ...   0.001457  -0.017101  -0.250963  -0.001457   
2 -0.083430 -0.452646  ...   0.080874  -0.039404  -0.331130  -0.080874   
3 -0.167492  0.083064  ...   0.261195  -0.074577  -0.281935  -0.261195   
4 -0.001720  0.167503  ...   0.181902  -0.063202  -0.364724  -0.181902   

   vx_1_1000  vy_1_1000  vz_1_1000  vx_2_1000  vy_2_1000  vz_2_1000  
0  -0.104210  -0.721673  -0.262195   0.104210   0.721673   0.262195  
1   0.167632   0.763737   0.546329  -0.167632  -0.763737  -0.546329  
2   0.128510   0.343728   0.494653  -0.128510  -0.343728  -0.494653  
3  -0.013481  -0.439943   0.074785   0.013481   0.439943  -0.074785  
4   0.074315  -0.030131   0.357845  -0.074315   0.030131  -0.357845  

[5 rows x 51 columns]

In [23]:
model = MultiOutputRegressor(GradientBoostingRegressor(n_estimators=100,
                                                        max_depth=10,
                                                        learning_rate=0.05)
                             , n_jobs=-1)

In [24]:
steps = 10
X, y = get_X_y(orbit2b, steps, False, True)

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [26]:
model.fit(X_train, y_train);

In [27]:
y_pred = model.predict(X_test)

In [28]:
error_10 = np.sqrt(mean_squared_error(y_test, y_pred, multioutput='raw_values'))

In [29]:
print(steps, error_10)

10 [0.03104747 0.03258146 0.03231733 0.31189676 0.30106    0.28878215]


In [30]:
y_test[0], y_pred[0]

(array([-0.74165933,  0.14831442,  0.71137436,  0.28519114, -0.42734128,
         0.4540127 ]),
 array([-0.73797076,  0.14163549,  0.71014875,  0.26978724, -0.42278812,
         0.47388515]))

In [31]:
steps = 100
X, y = get_X_y(orbit2b, steps, False, True)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [33]:
model.fit(X_train, y_train);

In [34]:
y_pred = model.predict(X_test)

In [35]:
error_100 = np.sqrt(mean_squared_error(y_test, y_pred, multioutput='raw_values'))

In [36]:
print(steps, error_100)

100 [0.14734377 0.14359409 0.14752757 0.55533449 0.57400712 0.55977747]


In [37]:
y_test[0], y_pred[0]

(array([ 0.36830901, -0.24293999, -0.70442531,  0.58837507,  0.12665705,
        -1.16203217]),
 array([-0.0166423 ,  0.03831879, -0.18481807,  0.59860548, -0.58160101,
        -0.99345631]))

In [38]:
steps = 1000
X, y = get_X_y(orbit2b, steps, False, True)

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [40]:
model.fit(X_train, y_train);

In [41]:
y_pred = model.predict(X_test)

In [42]:
error_1000 = np.sqrt(mean_squared_error(y_test, y_pred, multioutput='raw_values'))

In [43]:
print(steps, error_1000)

1000 [0.62596037 0.62695205 0.63112552 0.73196143 0.72423097 0.70729221]


In [44]:
y_test[0], y_pred[0]

(array([17.75481736, -1.11123136,  8.26362541,  0.58694654,  0.08725069,
         0.25774253]),
 array([17.67826472, -1.13529685,  8.230423  ,  0.55967471,  0.04261316,
         0.24207471]))

In [45]:
print(np.mean(error_10[:3]), np.mean(error_10[3:]))
print(np.mean(error_100[:3]), np.mean(error_100[3:]))
print(np.mean(error_1000[:3]), np.mean(error_1000[3:]))

0.03198208649896947 0.300579637723342
0.14615514408441144 0.5630396941670982
0.6280126451762782 0.7211615388886904
