In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
plt.style.use("ggplot")
%matplotlib inline

In [2]:
from transform import get_X_y
%load_ext autoreload
%autoreload 2

In [3]:
## import sklearn modules

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error

from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

In [4]:
orbit3b = pd.read_csv('../data/samples_3_bodies_3_dim_0_m_com.csv')

In [5]:
orbit3b.head()

sim_id       m_1       m_2       m_3    rx_1_0    ry_1_0    rz_1_0  \
0     0.0  1.612215  2.697331  2.113259 -2.296006  2.877565 -9.170347   
1     0.0  1.612215  2.697331  2.113259 -0.833236  2.025081 -4.682410   
2     0.0  1.612215  2.697331  2.113259 -1.386685  2.451587 -6.523806   
3     0.0  1.612215  2.697331  2.113259 -1.704009  2.637154 -7.498272   
4     0.0  1.612215  2.697331  2.113259 -2.050488  2.794998 -8.500527   

     rx_2_0    ry_2_0    rz_2_0  ...  rz_3_1000  vx_1_1000  vy_1_1000  \
0  0.706297 -0.899724  3.160373  ...   3.475327  -0.083728  -0.005456   
1  0.218571 -0.615884  1.653333  ...   2.564054  -0.142035   0.065775   
2  0.407949 -0.761911  2.265831  ...   2.923653  -0.120877   0.036916   
3  0.517432 -0.837350  2.580210  ...   3.123465  -0.108443   0.021664   
4  0.619787 -0.874291  2.936525  ...   3.362595  -0.094319   0.005680   

   vz_1_1000  vx_2_1000  vy_2_1000  vz_2_1000  vx_3_1000  vy_3_1000  vz_3_1000  
0  -0.182062  -0.644452   0.732823   1.021511   0.886446  -0.931201  -1.164945  
1  -0.412336  -0.434259   0.539911   0.856111   0.662640  -0.739314  -0.778154  
2  -0.324624  -0.367041   0.482402   0.731627   0.560703  -0.643894  -0.686181  
3  -0.275432   0.570784  -0.428765  -0.544556  -0.645808   0.530742   0.905192  
4  -0.221403   1.123254  -1.029775  -1.358825  -1.361748   1.310056   1.903292  

[5 rows x 76 columns]

In [6]:
model = MultiOutputRegressor(GradientBoostingRegressor(n_estimators=100,
                                                        max_depth=10,
                                                        learning_rate=0.05)
                             , n_jobs=-1)

In [7]:
steps = 10
X, y = get_X_y(orbit3b, steps, True, True)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [9]:
model.fit(X_train, y_train);

In [10]:
y_pred = model.predict(X_test)

In [11]:
error_10 = np.sqrt(mean_squared_error(y_test, y_pred, multioutput='raw_values'))

In [12]:
print(steps, error_10)

10 [0.10634406 0.13081029 0.09983919 0.11668779 0.12558851 0.10233444
 1.2460882  1.26835304 1.28346494 1.24455724 1.32063099 1.29342852]


In [13]:
y_test[0], y_pred[0]

(array([-0.0212074 ,  0.05786918,  0.10340571,  6.35841785, -5.05974478,
         2.08707043,  4.48820263,  1.4403444 ,  4.63768072,  4.0429869 ,
        -0.42092539,  2.9614225 ]),
 array([ 1.24900654e-01, -2.56851984e-03,  5.99461044e-02,  6.40250199e+00,
        -5.03837826e+00,  2.07413678e+00,  3.53615256e+00,  2.15859639e-01,
         1.15461490e+00,  2.51089281e+00, -1.34723055e+00,  2.17838316e+00]))

In [14]:
steps = 100
X, y = get_X_y(orbit3b, steps, True, True)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [16]:
model.fit(X_train, y_train);

In [17]:
y_pred = model.predict(X_test)

In [18]:
error_100 = np.sqrt(mean_squared_error(y_test, y_pred, multioutput='raw_values'))

In [19]:
print(steps, error_100)

100 [0.42339271 0.43901707 0.43301599 0.41831902 0.42988443 0.43844981
 1.75490266 1.69710654 1.71512836 1.74257057 1.76328146 1.75297329]


In [20]:
y_test[0], y_pred[0]

(array([ 0.65854114, -0.44599993, -0.0143216 ,  0.36742115, -0.25321638,
        -0.29682612, -4.21227887,  0.31452547, -1.54282593, -1.06804264,
         3.53574915, -3.02605914]),
 array([ 0.83490599, -0.07289022,  0.17358697,  0.65795846, -0.75142212,
         0.39506493, -0.3854041 , -0.12283646, -0.07829692, -0.81251712,
         0.04893581, -0.88141298]))

In [21]:
steps = 1000
X, y = get_X_y(orbit3b, steps, True, True)

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [23]:
model.fit(X_train, y_train);

In [24]:
y_pred = model.predict(X_test)

In [25]:
error_1000 = np.sqrt(mean_squared_error(y_test, y_pred, multioutput='raw_values'))

In [26]:
print(steps, error_1000)

1000 [2.30088161 2.55027064 2.56757207 2.25216087 2.5359357  2.49565635
 1.90371438 1.85801274 1.90176437 1.84061523 1.82529477 1.85392456]


In [27]:
y_test[0], y_pred[0]

(array([ 2.3540578 ,  3.57844179,  5.09628087,  2.24048452,  3.28154838,
         4.4641659 ,  0.01592813,  0.76355449, -1.44826402,  0.9359095 ,
        -0.41764359,  0.73081706]),
 array([-0.60185522, -0.79550052,  0.31063126, -0.29793796,  0.06320216,
         0.02928218, -0.23171262, -1.1995528 , -0.03307144, -0.20304   ,
        -0.2515698 ,  0.44507425]))

In [29]:
print(np.mean(error_10[:6]), np.mean(error_10[6:]))
print(np.mean(error_100[:6]), np.mean(error_100[6:]))
print(np.mean(error_1000[:6]), np.mean(error_1000[6:]))

0.1136007140203839 1.2760871537216776
0.43034650674835967 1.7376604816844348
2.450412875215651 1.8638876745654425
