In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
plt.style.use("ggplot")
%matplotlib inline

In [2]:
from transform import get_X_y
%load_ext autoreload
%autoreload 2

In [3]:
## import sklearn modules

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error

from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

In [4]:
orbit3b = pd.read_csv('../data/samples_3_bodies_3_dim_1_m_com.csv')

In [5]:
orbit3b.head()

sim_id  m_1  m_2  m_3    rx_1_0    ry_1_0    rz_1_0    rx_2_0    ry_2_0  \
0     0.0  1.0  1.0  1.0 -1.871301 -2.006454 -4.019154  1.036887  1.102577   
1     0.0  1.0  1.0  1.0 -0.795995 -0.784647 -2.908840  0.550239  0.475886   
2     0.0  1.0  1.0  1.0 -1.286293 -1.327033 -3.676037  0.781252  0.669198   
3     0.0  1.0  1.0  1.0 -1.531398 -1.604794 -3.942117  0.923130  0.881083   
4     0.0  1.0  1.0  1.0 -1.754476 -1.864324 -4.064955  1.039760  1.002777   

     rz_2_0  ...  rz_3_1000  vx_1_1000  vy_1_1000  vz_1_1000  vx_2_1000  \
0  1.914704  ...   1.506755   0.058465   0.055659   0.251354   0.468752   
1  1.411803  ...   1.914033  -0.093075  -0.108049  -0.055457   1.271687   
2  1.907524  ...   2.037791  -0.051280  -0.063582   0.041273   0.165383   
3  1.939458  ...   1.849364  -0.022043  -0.032130   0.102739   1.351800   
4  2.016291  ...   1.675857   0.018660   0.012058   0.181290   1.472221   

   vy_2_1000  vz_2_1000  vx_3_1000  vy_3_1000  vz_3_1000  
0   0.637606  -0.860091  -0.527217  -0.693265   0.608736  
1   0.664929  -0.215485  -1.178611  -0.556880   0.270943  
2  -0.955880   1.572582  -0.114103   1.019462  -1.613855  
3   0.572655  -0.143771  -1.329757  -0.540525   0.041031  
4   0.435378   0.073873  -1.490881  -0.447436  -0.255163  

[5 rows x 76 columns]

In [6]:
model = MultiOutputRegressor(GradientBoostingRegressor(n_estimators=100,
                                                        max_depth=10,
                                                        learning_rate=0.05)
                             , n_jobs=-1)

In [7]:
steps = 10
X, y = get_X_y(orbit3b, steps, False, True)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [9]:
model.fit(X_train, y_train);

In [10]:
y_pred = model.predict(X_test)

In [11]:
print(steps, np.sqrt(mean_squared_error(y_test, y_pred)))

10 0.44162589578527767


In [12]:
y_test[0], y_pred[0]

(array([-0.17310813,  0.59769776, -0.22911571,  1.91007486,  0.72790788,
        -1.15223583,  1.23016267,  0.37597501,  0.55421817,  1.15847604,
         0.72919834, -0.40290953]),
 array([-0.17346954,  0.596465  , -0.2334102 ,  1.89515989,  0.72485577,
        -1.1463901 ,  1.31291943,  0.47034863,  0.53357898,  1.10609049,
         0.75331009, -0.3597517 ]))

In [13]:
steps = 100
X, y = get_X_y(orbit3b, steps, False, True)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [15]:
model.fit(X_train, y_train);

In [16]:
y_pred = model.predict(X_test)

In [17]:
print(steps, np.sqrt(mean_squared_error(y_test, y_pred)))

100 0.6883552137643727


In [18]:
y_test[0], y_pred[0]

(array([ 0.21824369,  0.55553232,  0.23371509,  0.06352748, -0.88279085,
        -1.08881746,  1.6897147 , -1.20288577,  1.19798883,  1.67307464,
        -0.33485499,  0.54977548]),
 array([ 0.09969665,  0.60567152,  0.01334005, -0.04574904, -0.75061896,
        -1.07076164,  0.92148356, -1.0605468 ,  0.53810326,  1.19490091,
         0.34878791,  0.55756814]))

In [19]:
steps = 1000
X, y = get_X_y(orbit3b, steps, False, True)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [21]:
model.fit(X_train, y_train);

In [22]:
y_pred = model.predict(X_test)

[autoreload of transform failed: Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/home/ec2-user/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/home/ec2-user/anaconda3/envs/tensorflow2_p36/lib/python3.6/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/home/ec2-user/anaconda3/envs/tensorflow2_p36/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen impo

In [23]:
print(steps, np.sqrt(mean_squared_error(y_test, y_pred)))

1000 1.23045057770961


In [24]:
y_test[0], y_pred[0]

(array([-0.47152705,  0.32451766, -0.84652701, -0.54962493,  0.3696738 ,
        -1.05321126,  1.13238854,  1.86377375, -1.20634592, -0.45614608,
         0.96123473,  1.95053724]),
 array([-0.05833752, -0.22117921,  0.01524844,  0.1501733 , -0.11214359,
         0.15479875, -0.0484263 ,  0.02964908,  0.21531185, -0.08198046,
        -0.00864177,  0.06873894]))