In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
plt.style.use("ggplot")
%matplotlib inline

In [2]:
from transform import get_X_y
%load_ext autoreload
%autoreload 2

In [3]:
## import sklearn modules

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error

from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

In [4]:
orbit3b = pd.read_csv('../data/samples_3_bodies_3_dim_1_m_com.csv')

In [5]:
orbit3b.head()

sim_id  m_1  m_2  m_3    rx_1_0    ry_1_0    rz_1_0    rx_2_0    ry_2_0  \
0     0.0  1.0  1.0  1.0 -1.871301 -2.006454 -4.019154  1.036887  1.102577   
1     0.0  1.0  1.0  1.0 -0.795995 -0.784647 -2.908840  0.550239  0.475886   
2     0.0  1.0  1.0  1.0 -1.286293 -1.327033 -3.676037  0.781252  0.669198   
3     0.0  1.0  1.0  1.0 -1.531398 -1.604794 -3.942117  0.923130  0.881083   
4     0.0  1.0  1.0  1.0 -1.754476 -1.864324 -4.064955  1.039760  1.002777   

     rz_2_0  ...  rz_3_1000  vx_1_1000  vy_1_1000  vz_1_1000  vx_2_1000  \
0  1.914704  ...   1.506755   0.058465   0.055659   0.251354   0.468752   
1  1.411803  ...   1.914033  -0.093075  -0.108049  -0.055457   1.271687   
2  1.907524  ...   2.037791  -0.051280  -0.063582   0.041273   0.165383   
3  1.939458  ...   1.849364  -0.022043  -0.032130   0.102739   1.351800   
4  2.016291  ...   1.675857   0.018660   0.012058   0.181290   1.472221   

   vy_2_1000  vz_2_1000  vx_3_1000  vy_3_1000  vz_3_1000  
0   0.637606  -0.860091  -0.527217  -0.693265   0.608736  
1   0.664929  -0.215485  -1.178611  -0.556880   0.270943  
2  -0.955880   1.572582  -0.114103   1.019462  -1.613855  
3   0.572655  -0.143771  -1.329757  -0.540525   0.041031  
4   0.435378   0.073873  -1.490881  -0.447436  -0.255163  

[5 rows x 76 columns]

In [6]:
model = MultiOutputRegressor(GradientBoostingRegressor(n_estimators=100,
                                                        max_depth=10,
                                                        learning_rate=0.05)
                             , n_jobs=-1)

In [7]:
steps = 10
X, y = get_X_y(orbit3b, steps, False, True)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [9]:
model.fit(X_train, y_train);

In [10]:
y_pred = model.predict(X_test)

In [11]:
error_10 = np.sqrt(mean_squared_error(y_test, y_pred, multioutput='raw_values'))

In [12]:
print(steps, error_10)

10 [0.04179739 0.03411312 0.03642888 0.04334737 0.05490527 0.04070807
 0.6120962  0.61843824 0.61926547 0.64656974 0.62657545 0.62022093]


In [13]:
y_test[0], y_pred[0]

(array([-0.25251427, -0.51872643, -0.51976833, -0.37137377, -0.32891991,
        -0.48351389,  0.51071664, -0.69387327, -1.76524899,  0.56052486,
        -3.44404561, -0.4390444 ]),
 array([-0.25081718, -0.52797198, -0.51444427, -0.37298955, -0.2858214 ,
        -0.4810121 ,  0.67264739, -1.3726809 , -1.76771742,  0.52617129,
        -2.53543956, -0.50939295]))

In [14]:
steps = 100
X, y = get_X_y(orbit3b, steps, False, True)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [16]:
model.fit(X_train, y_train);

In [17]:
y_pred = model.predict(X_test)

In [18]:
error_100 = np.sqrt(mean_squared_error(y_test, y_pred, multioutput='raw_values'))

In [19]:
print(steps, error_100)

100 [0.25020847 0.2489     0.25123052 0.25499652 0.25891803 0.2538403
 0.9380214  0.92769002 0.95478029 0.93623786 0.95059012 0.94767471]


In [20]:
y_test[0], y_pred[0]

(array([-0.03453428,  1.2819052 , -0.79950754, -0.72672522,  1.04209859,
        -0.85823423,  0.0867247 , -0.1344913 ,  0.57760159,  0.0741194 ,
         0.81047715,  0.53486433]),
 array([ 0.04195743,  1.44153653, -0.74228526, -0.59020279,  0.53995199,
        -0.79681636,  0.54874742,  0.55292672,  0.96839769, -0.04962332,
        -0.0250744 ,  0.86077827]))

In [21]:
steps = 1000
X, y = get_X_y(orbit3b, steps, False, True)

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [23]:
model.fit(X_train, y_train);

In [24]:
y_pred = model.predict(X_test)

In [25]:
error_1000 = np.sqrt(mean_squared_error(y_test, y_pred, multioutput='raw_values'))

In [26]:
print(steps, error_1000)

1000 [1.35946769 1.33993782 1.31802041 1.37262888 1.40553526 1.30711263
 1.09491065 1.08504871 1.10675491 1.11156702 1.10058498 1.08472105]


In [27]:
y_test[0], y_pred[0]

(array([ 0.57953647, -1.78930066, -6.38337398,  0.90943712, -1.64540677,
        -6.31609487,  0.5212999 , -0.58123435, -0.06660228, -0.79773887,
         0.34199434, -0.8437748 ]),
 array([ 2.85340891e-01, -2.75146551e-01, -2.88975588e+00,  5.20222361e-01,
        -3.32668416e-01, -5.13174655e+00,  4.49237184e-03,  4.39916211e-02,
        -4.38637698e-02, -2.43652832e-02,  8.36221901e-04, -7.41130007e-02]))

In [29]:
print(np.mean(error_10[:6]), np.mean(error_10[6:]))
print(np.mean(error_100[:6]), np.mean(error_100[6:]))
print(np.mean(error_1000[:6]), np.mean(error_1000[6:]))

0.04188334984284575 0.6238610056241741
0.2530156393751767 0.9424990659730773
1.3504504465683127 1.097264555619048
