In [90]:
import numpy as np
import pandas as pd
import pickle
from transform import get_X_y, transform_X_y, inverse_transform_X_y, normalize
from model_generator import *

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [91]:
with open('samples_2_bodies_3_dim_1_m_com_steps_10.pkl', 'rb') as f:
        model = pickle.load(f)

In [92]:
orbit2b = pd.read_csv('../data/samples_2_bodies_3_dim_1_m_com.csv')
X, y = get_X_y(orbit2b, 10, False, False)

In [93]:
X.shape

(200000, 12)

In [94]:
inverse_transform_X_y(model.predict_(transform_X_y(X[:2,:],2, False), transform=False), 2, False)

array([[ 0.07311469,  0.32115203,  0.24666064, -0.07311469, -0.32115203,
        -0.24666064,  0.00941661, -0.28234207,  0.20003969, -0.00941661,
         0.28234207, -0.20003969],
       [ 0.04568598,  0.04711983,  0.18948523, -0.04568598, -0.04711983,
        -0.18948523, -0.21710988, -0.98218564, -0.64115932,  0.21710988,
         0.98218564,  0.64115932]])

In [95]:
X[:2,:], y[:2,:]

(array([[ 0.07281155,  0.33968053,  0.23480664, -0.07281155, -0.33968053,
         -0.23480664,  0.03266844, -0.2460071 ,  0.23030966, -0.03266844,
          0.2460071 , -0.23030966],
        [ 0.05440708,  0.10524137,  0.2220554 , -0.05440708, -0.10524137,
         -0.2220554 , -0.1514587 , -0.82615856, -0.45092904,  0.1514587 ,
          0.82615856,  0.45092904]]),
 array([[ 0.07431854,  0.32285098,  0.24714994, -0.07431854, -0.32285098,
         -0.24714994,  0.01739261, -0.31477706,  0.18026482, -0.01739261,
          0.31477706, -0.18026482],
        [ 0.04353645,  0.05263279,  0.1875935 , -0.04353645, -0.05263279,
         -0.1875935 , -0.21588262, -0.92730709, -0.72122765,  0.21588262,
          0.92730709,  0.72122765]]))

In [96]:
model.predict_(X[:5,:], True)

array([[ 0.07311469,  0.32115203,  0.24666064, -0.07311469, -0.32115203,
        -0.24666064,  0.00941661, -0.28234207,  0.20003969, -0.00941661,
         0.28234207, -0.20003969],
       [ 0.04568598,  0.04711983,  0.18948523, -0.04568598, -0.04711983,
        -0.18948523, -0.21710988, -0.98218564, -0.64115932,  0.21710988,
         0.98218564,  0.64115932],
       [-0.0097771 , -0.04537326, -0.02215093,  0.0097771 ,  0.04537326,
         0.02215093, -0.04275323,  1.91208471, -0.94730372,  0.04275323,
        -1.91208471,  0.94730372],
       [ 0.06123634,  0.36077459,  0.18756358, -0.06123634, -0.36077459,
        -0.18756358,  0.05958586, -0.03937822,  0.34608129, -0.05958586,
         0.03937822, -0.34608129],
       [ 0.02151226,  0.28905452,  0.03110837, -0.02151226, -0.28905452,
        -0.03110837,  0.13918573,  0.54788286,  0.47729123, -0.13918573,
        -0.54788286, -0.47729123]])